### ISSUE TITLE
Overall review of structure and presentation

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/docs.openzeppelin.com#47]
We're doing an overall review of the site, redesigning some parts, and restructuring the content. Mainly we are making sure that all of our tools have a place in the site, and that we have guides introducing people to all of our tools and how to use them together.

This issue tracks all the related efforts.

#### Content
All projects should follow this structure: first Overview, then articles organized conceptually, finally API Reference.

- [x] Restructure Contracts documentation (https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2002)
- [x] Restructure SDK documentation (https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1286)
- [x] Restructure Starter Kits documentation (https://github.com/OpenZeppelin/starter-kit/issues/87)
- [ ] Create documentation for all other projects. Take from README as much as possible.
    - [x] test-helpers
    - [x] test-environment
    - [x] network
    - [x] gsn-helpers
    - [x] gsn-provider
    - [ ] solidity-hot-loader
    - [x] contract-loader
    - [ ] solidity-docgen
- [x] Create "entry guides" section in the site (potential name: "Learn") (some of these may be links to guides elsewhere in the site)
    - [x] Deploying a smart contract
    - [x] Writing smart contracts (Contracts)
    - [x] Managing a smart contract project (CLI / Upgrades)
    - [x] Interacting with your contracts (CLI / loader / hot-loader)
    - [x] Testing contracts (Test-env / Test-helpers)
    - [x] About the GSN (Contracts / GSN helpers / GSN provider (include "building a gsn dapp"))
    - [x] About upgrades (CLI / Upgrades)
    - [x] About dapps (CLI / Network.js / Starter kit / hot loader (include "writing a dapp"))
- [ ] Include a link to our audits service in the warning boxes

#### Design
- [x] Redesing sidebar to accomodate the bigger list of tools, and one or two more levels of depth, with collapsible indicators
- [x] Make sure more than one level of depth works in the sidebar
- [x] Redesign landing page
- [ ] Design a nice footer for all pages promoting the forum as a place for questions and suggestions

#### Infrastructure
- [x] Fix current errors preventing publishing sdk@2.6 docs
- [x] Fix caching of the build on Netlify
- [x] Fix build previews for the repos ([OpenZeppelin/docs-utils](https://github.com/OpenZeppelin/docs-utils))
- [x] Add Antora structure to all new repos
    - [x] test-env (https://github.com/OpenZeppelin/openzeppelin-test-environment/pull/28)
    - [x] test-helpers (https://github.com/OpenZeppelin/openzeppelin-test-helpers/pull/100)
    - [x] network
    - [x] gsn-helpers
    - [x] gsn-provider
    - [x] hot-loader
    - [x] contract-loader
    - [x] solidity-docgen (https://github.com/OpenZeppelin/solidity-docgen/commit/979c42bbad2c7ab6967802f34454f1fe29d600c7)
- [x] Add Netlify webhooks to all new repos added to the site
- [ ] Create automation to merge docs changes to the branches used for the site
- [ ] Use JavaScript/TypeScript documentation generators for API reference
- [x] Add redirects from the old pages (https://github.com/OpenZeppelin/netlify-redirects/issues/1)

**Comment by nventuro** [comment]
Considering this finished as of #113. Will open new issues for unresolved tasks.
